### ISSUE TITLE
dicom2nifti

### ISSUE THREAD

**Issue by Dale-Black** [felixhorger/DICOMTools.jl#1]
Hey, this is way easier said than done and I don’t need this functionality right away, but I was wondering if you had any interest in making a dicom2nifti function? I know parts of this have been worked on in the NIfTI.jl library but it hasn’t been fully fleshed out I don’t think

**Comment by felixhorger** [comment]
Hi Dale,

I haven't worked with niftis before, but I have heard that they are much easier to work with in certain regards.
Indeed there is an example: which may or may not work ^^ (https://github.com/JuliaNeuroscience/NIfTI.jl/blob/ad8e8222ef367dc81cf950e1a8bd610729c880d4/examples/dicom2nifti.jl)

Also, I'd prefer to have this functionality in the Nifti package because DICOM is the "first" format you get from any medical scanner. So, people who don't need niftis, will not see the dcm2nifti function in this module working on dicoms only, but people who know they want to work with niftis will use the nifti package anyways.

I'm sorry to say that, but here I can't really be of any help. I wish you good luck with getting the example to work!

Cheers,
Felix
